### PR TITLE
Move documentation into README.markdown and doc/gnupg.txt

### PR DESCRIPTION
**Pull request by Koronen**
- Moves general documentation, such as the description and installation instructions, to a new README file at the root of the repo.
- Moves detailed documentation, such at command descriptions, into a text file under doc/ that can be indexed and searched through using Vim's `:help` command.

### CODE REVIEW

**Comment by lucc** [comment]
@jamessan are you still interested in this patch?

I was about to propose a pull request to put a lot of function definitions into the autoload directory. But as I see here you did not merge this for a long time. So I want to ask: Are you even interested in pull requests that change the folder layout of the plugin?

**Comment by jamessan** [comment]
I do plan on making changes similar to this.  I've been holding off on this for other reasons, but will look into doing it soon.

**Comment by lucc** [comment]
By "similar to this" do you mean the documentation change or the autoload functions? If you want I can open a PR to move function definitions to the autoload directory.

**Comment by jamessan** [comment]
I mean both.

**Pull request merged**
