### PR TITLE
Change GPGFilePattern to include more files

### PR DESCRIPTION
**Pull request by ghost**
This extra change allows for file patterns like x.gpg.py or x.gpg.pl in addition to the normal x.gpg This allows the filetype plugin to correctly use highlighting while still providing the gpg transparent encryption. Tested this on my machine, works for common script files. Doesnt work with vimwiki for some reason though.

### CODE REVIEW

**Comment by jamessan** [comment]
> This extra change allows for file patterns like x.gpg.py or x.gpg.pl in addition to the normal x.gpg

Don't `x.py.gpg` and `x.pl.gpg` already work?

**Comment by ghost** [comment]
> 

This is so that highlighting works. It doesn't work when the suffix is .gpg

**Comment by msva** [comment]
@majorendian 
didn't you try to add vim-comments in top or end of the file?
Like
```
# vim: ft=python

def myFunn():
...
```

**Comment by msva** [comment]
(and, by the way, semantically, keeping `gpg` at the end of file name is better, as it corresponds the real content of the file: gpg-encrypted message.
The python/perl is are inside the, let's call it "crypto container".

**Comment by ghost** [comment]
I suppose the modline really is a far better idea. You can close this and reject the pr.

**Pull request closed without merging**
